version: '3.8'
services:

  # nginx:
  #   build: .
  #   ports:
  #     - "8081:81"
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  public_assets:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /public_assets:/home/public_assets

