version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ayuamritwellness:latest
    container_name: ayuamritwellness
    ports:
      - "8081:81"
    restart: unless-stopped

